### ISSUE TITLE
win11_custom_iso all to remove all, none to remove none

### ISSUE THREAD

**Issue by Cyberavater** [daboynb/windows_scripts#1]
no need to repeat if, we want same choice for all.

**Comment by Cyberavater** [comment]
Also, is it possible to provide all preference beforehand so that it can run unattended?

**Comment by daboynb** [comment]
> no need to repeat if, we want same choice for all.

Hi, this program is used on a telegram channel too and the users asked me to do that. 
I can edit the script to ask : 
- remove all features
- none
- manually select

**Comment by daboynb** [comment]
> Also, is it possible to provide all preference beforehand so that it can run unattended?

the only thing that it asks is the layout, you can add it inside the unattend.xml

example ->  https://github.com/daboynb/windows_scripts/blob/main/win10_custom_iso%20_italian/resources/unattend.xml

this is for the italian iso
