### ISSUE TITLE
Kaspersky

### ISSUE THREAD

**Issue by androidghosh** [daboynb/windows_scripts#2]
Kaspersky Total Security has changed into Kaspersky Premium Protection. Name of Internet Security also changed to Kaspersky Plus. Will the same script work? Can you update the script so that it also works on newer versions?

**Comment by androidghosh** [comment]
It's closed, does that mean it works now?

**Comment by daboynb** [comment]
Nope, sorry, I still haven't figured it out. I will update this issue when I have found a way to do it.
