### ISSUE TITLE
Stuck on downloading Rufus

### ISSUE THREAD

**Issue by AndnixSH** [daboynb/windows_scripts#5]
I'm creating custom Win11 Pro ISO. When it downloads forked Rufus, it repeatedly downloading Rufus and never proceed to continue

![image](https://github.com/daboynb/windows_scripts/assets/40742924/fb7a8eb6-b9da-45c1-a3b6-4ee77f938e56)

**Comment by daboynb** [comment]
I'm unable to reproduce the issue on my machine, I will try a workaround.

**Comment by daboynb** [comment]
Can you try the new version?

**Comment by AndnixSH** [comment]
The CMD closes as soon as it tries to run Rufus

**Comment by daboynb** [comment]
Do you have a strange desktop path? Like with a cloud sync? I'm still not able to reproduce the issue on my machine. Btw I will try to figure out how to fix that.

**Comment by AndnixSH** [comment]
Now I got an error creating ISO file

```
Building the ISO

OSCDIMG 2.56 CD-ROM and DVD-ROM Premastering Utility
Copyright (C) Microsoft, 1993-2012. All rights reserved.
Licensed only for producing Microsoft authorized content.


Scanning source tree (500 files in 46 directories)
Scanning source tree complete (946 files in 89 directories)

Computing directory information complete

Image file is 6167003136 bytes (before optimization)

ERROR: Unable to create file "C:\Windows_iso_maker\Windows11_defender_disabled_edge_not_removed.iso" of 6167003136 bytes
Error 3
"ERROR: Can't build the ISO"
Press any key to continue . . .
```


Would it be a better idea to prompt to choose location to save ISO file?

**Comment by daboynb** [comment]
The real problem is that the testers are not encountering any issues, so I need to understand why, btw when at home I will put the choice for the location of the iso file.
Do you want a pre built iso in the meantime?

**Comment by daboynb** [comment]
I made the change that you suggested, now you can select where the ISO will be created.

**Comment by daboynb** [comment]
Is the issue fixed?

**Comment by AndnixSH** [comment]
sorry for late reply, it is fixed now
