### ISSUE TITLE
Add option to use previously downloaded iso in custom iso maker

### ISSUE THREAD

**Issue by lovwanshichetan** [daboynb/windows_scripts#6]
It just said online iso download failed then exited then i downloaded from browser but then the script still prompted me to download & shows usable download. I have to remove some line from script to make it work(although it resulted in non-bootable iso, seems like i have to learn bash now).

**Comment by lovwanshichetan** [comment]
Also, it resulted in increase in size of iso by 5gb, although i only removed lines which were prompting me to download from net & kept the part which asks to select iso from system.

**Comment by daboynb** [comment]
Hi, I don't understand your issue, can you provide a screenshot ? There's not an error message like "online iso download failed".
