### ISSUE TITLE
wrong OS displayed in windows custom iso maker

### ISSUE THREAD

**Issue by D3ENNY** [daboynb/windows_scripts#8]
in that script https://github.com/daboynb/windows_scripts/tree/main/windows_custom_iso_maker it display that i'm on windows 10 pro, when actaully i'm using windows 11 pro
![Senza titolo](https://github.com/daboynb/windows_scripts/assets/83723555/d55d975f-afae-471a-a843-731b379d2589)

**Comment by MrNico98** [comment]
not work 

try
# Get Windows version and edition
$osInfo = Get-WmiObject Win32_OperatingSystem
$winVersion = $osInfo.Version
$edition = $osInfo.Caption -replace '^.*(?=Windows \d+)', '' -replace '\d+$', '' -replace 'Microsoft', '' -replace 'TM', '' -replace '®', '' -replace 'E', ''
$arch = $osInfo.OSArchitecture

# Create label text with the gathered information
$labelText = "Windows Version: $winVersion`n`nEdition: $edition`n`nArchitecture: $arch`n`n"


sorry taki...sorry denny...
